optionales GitHub-Profil inkl. Link auf MeineSeite ergänzt
dee-dw/bewerbung-latex pull request #7
Opened 2021-02-18 22:31 UTC by dgehlich

Hallo,
ich habe auf der Seite _Zu meiner Person_ die optionale Möglichkeit für die Angabe eines GitHub-Profils inkl. Link ergänzt.
PDF wurde entspr. neu gebaut.

Grüße
Dominik

2021-02-22 20:55 UTC, dee-dw requested changes
Danke für den Request. Könntest Du die Reihenfolge in der Darstellung noch anpassen, sodass zuerst Xing, dann LinkedIn und dann erst GitHub definiert und auch angezeigt wird? Grund ist, dass für den Normalbewerber GitHub die kleinere Rolle spielt, ein Xing- oder Linked-Profil haben dagegen sehr viele.

Danke Dee

2021-02-22 21:17 UTC, dgehlich commented
Erledigt. Alles darunter geschoben.

2021-02-23 11:38 UTC, dgehlich commented
Vorsicht. Da ist aktuell noch ne "Bug". Es muss alles 3 gefüllt sein, damits aussieht. Bei nicht definierten Inhalten wird eine Leerzeile erzeugt. Bin dran.

![grafik](https://user-images.githubusercontent.com/54844544/108838563-17569980-75d4-11eb-9191-e62aa91e95c7.png)

2021-02-23 12:24 UTC, dgehlich commented
So. Ich hab das jetzt gelöst, indem dynamisch auf die Profile reagiert wird:
Wenn Profil (Xing, LinkedIn oder GitHub) angegeben, dann diese Zeile einfügen.

Die Frage hier ist, ob der nachfolgende Text dann auch dynamisch reagieren soll, oder ob es besser ist, nach den Profilen entspr. Leerzeilen hinzufügen (Bei keinen Profil: 3, bei einem: 2, bei zwei: 1, bei allen: 0).

2021-02-24 20:35 UTC, dee-dw commented
> Die Frage hier ist, ob der nachfolgende Text dann auch dynamisch reagieren soll, oder ob es besser ist, nach den Profilen entspr. Leerzeilen hinzufügen (Bei keinem Profil: 3, bei einem: 2, bei zwei: 1, bei allen: 0).

Optimalerweise ja. Sprich, egal, welche Zeilen man angibt, sollte der danach kommende Text sich nicht verschieben.

2021-02-25 09:34 UTC, dgehlich commented
Erledigt.
Es werden jetzt Leerzeilen entspr. der leeren Profile am Ende des Profilblocks ergänzt.
Ich habs analog `\DefTelefon` bei `% Absender` aufgebaut und mit Kommentaren versehen.

Ergebnis insgesamt:
* optionales GitHub-Profil bereitgestellt. Reihenfolge: Xing, LinkedIn, GitHub
* Lücke (Leerzeile) bei fehlenden Xing-Profil gefixt. Alle vorhandenen Profile werden direkt nach Angabe der Email angezeigt.
* nachfolgender Text bleibt in Position

2021-02-25 18:51 UTC, dee-dw approved these changes
Sieht gut aus, danke. Ggf. Mache ich noch eine kleine Änderung, aber das teste ich erst noch bei mir mit Deinen Änderungen.

2021-02-25 18:52 UTC, merged